# Generated by Django 6.0.5 on 2026-05-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_categories'),
        ('courses', '0017_alter_course_options_alter_usersubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='candidate_category',
            field=models.ForeignKey(blank=True, help_text='Catégorie sélectionnée par le candidat lors de son inscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='courses.category', verbose_name='catégorie choisie'),
        ),
    ]
