# Generated by Django 6.0.5 on 2026-05-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_correction_quiz_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'SUJET', 'verbose_name_plural': 'SUJETS'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-year', '-month', 'category__name', 'user__username'], 'verbose_name': 'abonnement mensuel', 'verbose_name_plural': 'abonnements mensuels'},
        ),
        migrations.RenameIndex(
            model_name='examquizattempt',
            new_name='courses_exa_exam_id_b7cf20_idx',
            old_name='courses_exa_exam_id_6a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='examquizattempt',
            new_name='courses_exa_exam_id_99ace6_idx',
            old_name='courses_exa_exam_id_9c4e1a_idx',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel'), ('pack', 'Tranche (pack de mois)')], default='monthly', help_text='Mensuel : pas de mois à lister. Annuel ou tranche : ajoutez les mois inclus dans la liste en bas de page.', max_length=20, verbose_name='type de formule'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanmonth',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_grants', to='courses.subscriptionplan', verbose_name='formule'),
        ),
        migrations.AddIndex(
            model_name='monthlycorrection',
            index=models.Index(fields=['category', '-year', '-month'], name='courses_mon_categor_30e14f_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycoursecontent',
            index=models.Index(fields=['category', '-year', '-month'], name='courses_mon_categor_2f08c3_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyexam',
            index=models.Index(fields=['category', '-year', '-month'], name='courses_mon_categor_9f045d_idx'),
        ),
    ]
