# Generated by Django 6.0.5 on 2026-06-13 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_options_alter_usersubscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscriptionrequest',
            index=models.Index(fields=['status', '-decided_at'], name='courses_sub_status_e90e81_idx'),
        ),
    ]
